# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{random_text}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Boba Fat"]
  s.date = %q{2009-12-30}
  s.executables = ["lorem", "vesna"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/lorem",
     "bin/vesna",
     "lib/random_text.rb",
     "lib/random_text/dictionary.rb",
     "lib/random_text/random_strings.rb",
     "random_text.gemspec",
     "resources/lorem.txt",
     "resources/vesna.txt",
     "spec/random_text/dictionary_spec.rb",
     "spec/random_text/random_string_spec.rb",
     "spec/random_text_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/toy/random_text}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Library to generate random strings}
  s.test_files = [
    "spec/random_text/dictionary_spec.rb",
     "spec/random_text/random_string_spec.rb",
     "spec/random_text_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

